### ISSUE TITLE
Fails to build for android

### ISSUE THREAD

**Issue by ToposStudio** [AgoraIO-Community/Agora-Unreal-SDK#17]
I read that this supported Android, but just like the blueprint version, this SDK throws the same error when I try to package for Android in UE4. 4.26 using the latest 1103 version of the plugin. Building android ASTC

`UATHelper: Packaging (Android (ASTC)):     ld.lld: error: undefined symbol: createAgoraRtcEngine  

UATHelper: Packaging (Android (ASTC)):     >>> referenced by AgoraRtcEngine.cpp:45 (H:/Work\SVN\develop\client\Topos_Rotunda_20211209\Plugins\AgoraPlugin\Source\AgoraPlugin\Private\AgoraRtcEngine.cpp:45)

UATHelper: Packaging (Android (ASTC)):     >>>               H:/Work/SVN/develop/client/Topos_Rotunda_20211209/Plugins/AgoraPlugin/Intermediate/Build/Android/UE4/Development/AgoraPlugin/Module.AgoraPlugin.cppa8.o:(agora::rtc::ue4::AgoraRtcEngine::createAgoraRtcEngine())

UATHelper: Packaging (Android (ASTC)):   

UATHelper: Packaging (Android (ASTC)):     ld.lld: error: undefined symbol: agora::rtc::IRtcEngine::release(bool)

UATHelper: Packaging (Android (ASTC)):     >>> referenced by AgoraRtcEngine.cpp:72 (H:/Work\SVN\develop\client\Topos_Rotunda_20211209\Plugins\AgoraPlugin\Source\AgoraPlugin\Private\AgoraRtcEngine.cpp:72)

UATHelper: Packaging (Android (ASTC)):     >>>               H:/Work/SVN/develop/client/Topos_Rotunda_20211209/Plugins/AgoraPlugin/Intermediate/Build/Android/UE4/Development/AgoraPlugin/Module.AgoraPlugin.cppa8.o:(agora::rtc::ue4::AgoraRtcEngine::release(bool))

UATHelper: Packaging (Android (ASTC)):     clang++: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by ToposStudio** [comment]
Additional note here: I unchecked "use arm 64" for android and it built (the armv7 version). So whatever build error is here is related to arm64. Maybe this will help you figure out the error.

And while it does build without error, it crashes on the quest as soon as the program is started.

**Comment by alexhajdu** [comment]
@ToposStudio I've got no issues with packaging both `1101` and `1103` and running it on Samsung S21. 
Previously, we had the Blueprint version running on the Quest2 but I understand it's obsolete now so I've rewritten it (see `Agora-Unreal-SDK/Agora-Unreal-QuickStart/API_Example/Source/Agora_Unreal_Video/`) and it was working correctly. What is the crash log? It's possibly not related to the Agora.

**Comment by ToposStudio** [comment]
I'm working on getting the crash logs from the quest. It gives no usable information in the headset as it is. This app has been built dozens of times for the quest and always ran without issue. Since the last time it was built the only thing added was Agora, so I can't really see what else it would be. It does run in the editor, so the implementation appears to be correct. 

I was able to finally get these logs from the quest: 


```
01-06 11:21:53.312 10119 12054 12054 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 12054 (main), pid 12054 (main)
01-06 11:21:53.335  1000   733 11873 I FrameSetDispatcher: [HEADSET] Client thread stopping
01-06 11:21:53.336  1000   733   733 I FrameSetDispatcher: [HEADSET] Client thread joined
01-06 11:21:53.336  1000   733   733 I CameraClientManager: [HEADSET] Removed client - started clients: 2
01-06 11:21:53.343 10119 12093 12093 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-06 11:21:53.344 10119 12093 12093 F DEBUG   : Build fingerprint: 'oculus/hollywood/hollywood:10/QQ3A.200805.001/21985310426300000:user/release-keys'
01-06 11:21:53.344 10119 12093 12093 F DEBUG   : Revision: '0'
01-06 11:21:53.344 10119 12093 12093 F DEBUG   : ABI: 'arm'
01-06 11:21:53.344 10119 12093 12093 F DEBUG   : Timestamp: 2022-01-06 11:21:53+0900
01-06 11:21:53.344 10119 12093 12093 F DEBUG   : pid: 12054, tid: 12054, name: main  >>> com.Topos.Topos_Gallery <<<
01-06 11:21:53.344 10119 12093 12093 F DEBUG   : uid: 10119
01-06 11:21:53.344 10119 12093 12093 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
01-06 11:21:53.344 10119 12093 12093 F DEBUG   :     r0  00000000  r1  00002f16  r2  00000006  r3  ff974d20
01-06 11:21:53.344 10119 12093 12093 F DEBUG   :     r4  ff974d18  r5  00002f16  r6  00002f16  r7  0000016b
01-06 11:21:53.344 10119 12093 12093 F DEBUG   :     r8  00000000  r9  ffffffff  r10 ebbb4410  r11 ebe532a0
01-06 11:21:53.344 10119 12093 12093 F DEBUG   :     ip  ff974d20  sp  ff974d00  lr  e99de301  pc  e99de312
01-06 11:21:53.344 10119 12093 12093 F DEBUG   : 
01-06 11:21:53.344 10119 12093 12093 F DEBUG   : backtrace:
01-06 11:21:53.344 10119 12093 12093 F DEBUG   :       #00 pc 0005e312  /apex/com.android.runtime/lib/bionic/libc.so (abort+94) (BuildId: d1568497ed5b358f7b37d4db225ec799)
01-06 11:21:53.345 10119 12093 12093 F DEBUG   :       #01 pc 0021742d  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xd4000) (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+280) (BuildId: 12099d3c2f6befffa1be7054c1dbdc9b)
01-06 11:21:53.973  1000  1045 12108 W ActivityTaskManager:   Force finishing activity com.Topos.Topos_Gallery/com.epicgames.ue4.GameActivity
01-06 11:21:53.982  1000  1045  5994 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=32, [ Transports: CELLULAR|WIFI|BLUETOOTH|ETHERNET|VPN Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&FOREGROUND Uid: 10119] ], android.os.BinderProxy@56dc2e5)
01-06 11:21:53.995  1000  1045  1084 I BootReceiver: Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)
01-06 11:21:53.999  1000  1045  1084 I DropBoxManagerService: add tag=SYSTEM_TOMBSTONE isTagEnabled=true flags=0x2
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: Exception thrown during pause
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: android.os.DeadObjectException
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: 	at android.os.BinderProxy.transactNative(Native Method)
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: 	at android.os.BinderProxy.transact(BinderProxy.java:511)
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: 	at android.app.IApplicationThread$Stub$Proxy.scheduleTransaction(IApplicationThread.java:2448)
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: 	at android.app.servertransaction.ClientTransaction.schedule(ClientTransaction.java:135)
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: 	at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:47)
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: 	at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:69)
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: 	at com.android.server.wm.ActivityStack.startPausingLocked(ActivityStack.java:1719)
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: 	at com.android.server.wm.ActivityStack.finishActivityLocked(ActivityStack.java:4067)
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: 	at com.android.server.wm.ActivityStack.finishActivityLocked(ActivityStack.java:4001)
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: 	at com.android.server.wm.ActivityStack.finishTopCrashedActivityLocked(ActivityStack.java:3886)
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: 	at com.android.server.wm.RootActivityContainer.finishTopCrashedActivities(RootActivityContainer.java:1195)
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: 	at com.android.server.wm.ActivityTaskManagerService$LocalService.finishTopCrashedActivities(ActivityTaskManagerService.java:7378)
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: 	at com.android.server.am.AppErrors.handleAppCrashLocked(AppErrors.java:754)
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: 	at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:605)
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: 	at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:494)
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: 	at com.android.server.am.AppErrors.crashApplication(AppErrors.java:409)
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9375)
01-06 11:21:54.007  1000  1045 12108 W ActivityTaskManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:84)
01-06 11:21:54.021  1000  1045 12109 I DropBoxManagerService: add tag=data_app_native_crash isTagEnabled=true flags=0x2
01-06 11:21:54.022  1000  1045  7049 I ActivityManager: Process com.Topos.Topos_Gallery (pid 12054) has died: fore TOP 

```

**Comment by ToposStudio** [comment]
Further troubleshooting:

I made a copy of this project. I ripped out all the c++ classes that i made as a copy of the demo project. I also went in and removed the child blueprint widget classes and packaged the project. 

This still crashed when loaded on oculus. I then went in and removed "agora" from the build.cs and unchecked 'agora' in the editor. 

Then built it again. 

The project loads just fine. 

Whatever this crash is, it's 100% related to agora being in the project as the plugin being enabled, but not even referenced causes it to crash.

**Comment by ToposStudio** [comment]
> @ToposStudio I've got no issues with packaging both `1101` and `1103` and running it on Samsung S21. Previously, we had the Blueprint version running on the Quest2 but I understand it's obsolete now so I've rewritten it (see `Agora-Unreal-SDK/Agora-Unreal-QuickStart/API_Example/Source/Agora_Unreal_Video/`) and it was working correctly. What is the crash log? It's possibly not related to the Agora.

So does that crashlog tell you anything about what is causing it or whether or not its related to agora?

**Comment by ToposStudio** [comment]
This issue was possibly caused by a conflict in the project. A clean version of the project has resulted in this mostly working
