### ISSUE TITLE
Solution: Agora + Unreal 5.02

### ISSUE THREAD

**Issue by anselmhook2** [AgoraIO-Community/Agora-Unreal-SDK#23]
I dug into Agora quite a bit and fixed a bug in the Agora UE4 middleware that prevents it from running on UE5. Here is a report on the issue and a diagnosis: https://stackoverflow.com/questions/72596102/how-to-solve-ue5-crashing-after-enabling-agora-plugin-and-opening-video-feed .

**Comment by oneSitDown** [comment]
Yes. The current version does have compatibility issues on unreal 5. Our current solution is similar to yours. Copy the VideoFrame data of the OnCaputerFrame callback to Tick and then perform the rendering operation. Can avoid crash problems
